repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(docs/.*|raw-data/.*|)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        types_or: [markdown]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
      - id: check-jsonschema
        name: "Check OpenAPI spec"
        files: static/openapi.yaml
        types: [yaml]
        args: ["--schemafile", "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json"]
