name: pre-commit
description: 'Action to run pre-commit based on the `.python-version` file'
author: Gert Van Gool
runs:
  using: composite
  steps:
    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@v5.1.0
      with:
        python-version-file: .python-version

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pre-commit

    - name: "Cache pre-commit scripts"
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.cache/pre-commit/
        key: |
          pre-commit-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Lint
      shell: bash
      run: pre-commit run --all-files --show-diff-on-failure
